---
resources:
- name: hello-repository
  type: git
  source:
    uri: https://github.com/fouadh/hellocpp.git
    branch: master

- name: cloudfoundry
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organization))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: deploy-hello
  serial: true
  plan:
  - get: hello-repository
    trigger: true

  - task: build-binary
    config:
      platform: linux
      inputs:
      - name: hello-repository
      outputs:
      - name: build
      image_resource:
        type: docker-image
        source: { repository: cloudfoundry/cflinuxfs3 }
      run:
        path: hello-repository/build.sh

  - put: cloudfoundry
    params:
      manifest: hello-repository/app/manifest.yml
      path: build/hello.zip
