---
resources:
- name: hello-repository
  type: git
  source:
    uri: https://github.com/fouadh/hellocpp.git
    branch: master

- name: cloudfoundry
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organization))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: deploy-hello
  serial: true
  plan:
  - get: hello-repository
    trigger: true
  - task: build-binary
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source: { repository: cloudfoundry/cflinuxfs3 }
      inputs:
      - name: hello-repository
      outputs:
      - name: build
      run:
        path: g++
        args: ["-o", "build/hello", "hello-repository/app/hello.cpp"]
  - put: cloudfoundry
    params:
      manifest: hello-repository/manifest
      path: build/hello
