---
resources:
- name: repository
  type: git
  source:
    uri: https://github.com/fouadh/hellocpp.git
    branch: master

- name: dockerhub
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/dockercpp

- name: cloudfoundry
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organization))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: deploy-app
  serial: true
  plan:
  - get: repository
    trigger: true

  - put: dockerhub
    params:
      build: repository

  - put: cloudfoundry
    params:
      manifest: repository/app/manifest-docker.yml
