kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deployments
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "patch"]